//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.10 at 04:01:49 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.gov.mec.portal.diplomadigital.arquivos_em_xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocumentacaoAcademicaRegistro_QNAME = new QName("http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", "DocumentacaoAcademicaRegistro");
    private final static QName _Diploma_QNAME = new QName("http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", "Diploma");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.gov.mec.portal.diplomadigital.arquivos_em_xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TLivroRegistro }
     * 
     */
    public TLivroRegistro createTLivroRegistro() {
        return new TLivroRegistro();
    }

    /**
     * Create an instance of {@link THistoricoEscolar }
     * 
     */
    public THistoricoEscolar createTHistoricoEscolar() {
        return new THistoricoEscolar();
    }

    /**
     * Create an instance of {@link THistoricoEscolar.MatrizCurricular }
     * 
     */
    public THistoricoEscolar.MatrizCurricular createTHistoricoEscolarMatrizCurricular() {
        return new THistoricoEscolar.MatrizCurricular();
    }

    /**
     * Create an instance of {@link THistoricoEscolar.MatrizCurricular.DisciplinaCursada }
     * 
     */
    public THistoricoEscolar.MatrizCurricular.DisciplinaCursada createTHistoricoEscolarMatrizCurricularDisciplinaCursada() {
        return new THistoricoEscolar.MatrizCurricular.DisciplinaCursada();
    }

    /**
     * Create an instance of {@link THistoricoEscolar.MatrizCurricular.DisciplinaCursada.Docentes }
     * 
     */
    public THistoricoEscolar.MatrizCurricular.DisciplinaCursada.Docentes createTHistoricoEscolarMatrizCurricularDisciplinaCursadaDocentes() {
        return new THistoricoEscolar.MatrizCurricular.DisciplinaCursada.Docentes();
    }

    /**
     * Create an instance of {@link TDadosIesRegistradora }
     * 
     */
    public TDadosIesRegistradora createTDadosIesRegistradora() {
        return new TDadosIesRegistradora();
    }

    /**
     * Create an instance of {@link TDadosIesEmissora }
     * 
     */
    public TDadosIesEmissora createTDadosIesEmissora() {
        return new TDadosIesEmissora();
    }

    /**
     * Create an instance of {@link TDadosPrivadosDiplomado }
     * 
     */
    public TDadosPrivadosDiplomado createTDadosPrivadosDiplomado() {
        return new TDadosPrivadosDiplomado();
    }

    /**
     * Create an instance of {@link TDocumentacaoComprobatoria }
     * 
     */
    public TDocumentacaoComprobatoria createTDocumentacaoComprobatoria() {
        return new TDocumentacaoComprobatoria();
    }

    /**
     * Create an instance of {@link TDiploma }
     * 
     */
    public TDiploma createTDiploma() {
        return new TDiploma();
    }

    /**
     * Create an instance of {@link TDocumentacaoAcademicaRegistro }
     * 
     */
    public TDocumentacaoAcademicaRegistro createTDocumentacaoAcademicaRegistro() {
        return new TDocumentacaoAcademicaRegistro();
    }

    /**
     * Create an instance of {@link TAtoRegulatorio }
     * 
     */
    public TAtoRegulatorio createTAtoRegulatorio() {
        return new TAtoRegulatorio();
    }

    /**
     * Create an instance of {@link TDadosDiplomado }
     * 
     */
    public TDadosDiplomado createTDadosDiplomado() {
        return new TDadosDiplomado();
    }

    /**
     * Create an instance of {@link TNaturalidade }
     * 
     */
    public TNaturalidade createTNaturalidade() {
        return new TNaturalidade();
    }

    /**
     * Create an instance of {@link TDadosRegistro }
     * 
     */
    public TDadosRegistro createTDadosRegistro() {
        return new TDadosRegistro();
    }

    /**
     * Create an instance of {@link TDadosDiploma }
     * 
     */
    public TDadosDiploma createTDadosDiploma() {
        return new TDadosDiploma();
    }

    /**
     * Create an instance of {@link TRg }
     * 
     */
    public TRg createTRg() {
        return new TRg();
    }

    /**
     * Create an instance of {@link TRegistroReq }
     * 
     */
    public TRegistroReq createTRegistroReq() {
        return new TRegistroReq();
    }

    /**
     * Create an instance of {@link TEndereco }
     * 
     */
    public TEndereco createTEndereco() {
        return new TEndereco();
    }

    /**
     * Create an instance of {@link TTermoResponsabilidade }
     * 
     */
    public TTermoResponsabilidade createTTermoResponsabilidade() {
        return new TTermoResponsabilidade();
    }

    /**
     * Create an instance of {@link TDadosCurso }
     * 
     */
    public TDadosCurso createTDadosCurso() {
        return new TDadosCurso();
    }

    /**
     * Create an instance of {@link TPessoa }
     * 
     */
    public TPessoa createTPessoa() {
        return new TPessoa();
    }

    /**
     * Create an instance of {@link TSeguranca }
     * 
     */
    public TSeguranca createTSeguranca() {
        return new TSeguranca();
    }

    /**
     * Create an instance of {@link TFiliacao }
     * 
     */
    public TFiliacao createTFiliacao() {
        return new TFiliacao();
    }

    /**
     * Create an instance of {@link TPolo }
     * 
     */
    public TPolo createTPolo() {
        return new TPolo();
    }

    /**
     * Create an instance of {@link TInfDiploma }
     * 
     */
    public TInfDiploma createTInfDiploma() {
        return new TInfDiploma();
    }

    /**
     * Create an instance of {@link TLivroRegistro.ResponsavelRegistro }
     * 
     */
    public TLivroRegistro.ResponsavelRegistro createTLivroRegistroResponsavelRegistro() {
        return new TLivroRegistro.ResponsavelRegistro();
    }

    /**
     * Create an instance of {@link THistoricoEscolar.MatrizCurricular.DisciplinaCursada.Docentes.Docente }
     * 
     */
    public THistoricoEscolar.MatrizCurricular.DisciplinaCursada.Docentes.Docente createTHistoricoEscolarMatrizCurricularDisciplinaCursadaDocentesDocente() {
        return new THistoricoEscolar.MatrizCurricular.DisciplinaCursada.Docentes.Docente();
    }

    /**
     * Create an instance of {@link TDadosIesRegistradora.Mantenedora }
     * 
     */
    public TDadosIesRegistradora.Mantenedora createTDadosIesRegistradoraMantenedora() {
        return new TDadosIesRegistradora.Mantenedora();
    }

    /**
     * Create an instance of {@link TDadosIesEmissora.Mantenedora }
     * 
     */
    public TDadosIesEmissora.Mantenedora createTDadosIesEmissoraMantenedora() {
        return new TDadosIesEmissora.Mantenedora();
    }

    /**
     * Create an instance of {@link TDadosPrivadosDiplomado.IngressoCurso }
     * 
     */
    public TDadosPrivadosDiplomado.IngressoCurso createTDadosPrivadosDiplomadoIngressoCurso() {
        return new TDadosPrivadosDiplomado.IngressoCurso();
    }

    /**
     * Create an instance of {@link TDocumentacaoComprobatoria.Documento }
     * 
     */
    public TDocumentacaoComprobatoria.Documento createTDocumentacaoComprobatoriaDocumento() {
        return new TDocumentacaoComprobatoria.Documento();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDocumentacaoAcademicaRegistro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", name = "DocumentacaoAcademicaRegistro")
    public JAXBElement<TDocumentacaoAcademicaRegistro> createDocumentacaoAcademicaRegistro(TDocumentacaoAcademicaRegistro value) {
        return new JAXBElement<TDocumentacaoAcademicaRegistro>(_DocumentacaoAcademicaRegistro_QNAME, TDocumentacaoAcademicaRegistro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDiploma }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", name = "Diploma")
    public JAXBElement<TDiploma> createDiploma(TDiploma value) {
        return new JAXBElement<TDiploma>(_Diploma_QNAME, TDiploma.class, null, value);
    }

}
