//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.fabricads.gov.handler.XMLGregorianCalendarAdapter;


/**
 * Ato regulatório de reconhecimento
 * 
 * <p>Java class for TAtoRegulatorioComOuSemEMEC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAtoRegulatorioComOuSemEMEC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tipo" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TTipoAtoComAtoProprio"/>
 *         &lt;element name="Numero" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNumeroAto"/>
 *         &lt;element name="Data" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *         &lt;element name="VeiculoPublicacao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString" minOccurs="0"/>
 *         &lt;element name="DataPublicacao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData" minOccurs="0"/>
 *         &lt;element name="SecaoPublicacao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TSecaoPublicacao" minOccurs="0"/>
 *         &lt;element name="PaginaPublicacao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TPaginaPublicacao" minOccurs="0"/>
 *         &lt;element name="NumeroDOU" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNumeroDOU" minOccurs="0"/>
 *         &lt;element name="InformacoesTramitacaoEMEC" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TInformacoesTramitacaoEMEC" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAtoRegulatorioComOuSemEMEC", propOrder = {
    "tipo",
    "numero",
    "data",
    "veiculoPublicacao",
    "dataPublicacao",
    "secaoPublicacao",
    "paginaPublicacao",
    "numeroDOU",
    "informacoesTramitacaoEMEC"
})
public class TAtoRegulatorioComOuSemEMEC {

    @XmlElement(name = "Tipo", required = true)
    @XmlSchemaType(name = "string")
    protected TTipoAtoComAtoProprio tipo;
    @XmlElement(name = "Numero", required = true)
    protected String numero;
    @XmlElement(name = "Data", required = true)
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(XMLGregorianCalendarAdapter.class)
    protected XMLGregorianCalendar data;
    @XmlElement(name = "VeiculoPublicacao")
    protected String veiculoPublicacao;
    @XmlElement(name = "DataPublicacao")
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(XMLGregorianCalendarAdapter.class)
    protected XMLGregorianCalendar dataPublicacao;
    @XmlElement(name = "SecaoPublicacao")
    @XmlSchemaType(name = "unsignedInt")
    protected Long secaoPublicacao;
    @XmlElement(name = "PaginaPublicacao")
    @XmlSchemaType(name = "unsignedInt")
    protected Long paginaPublicacao;
    @XmlElement(name = "NumeroDOU")
    @XmlSchemaType(name = "unsignedInt")
    protected Long numeroDOU;
    @XmlElement(name = "InformacoesTramitacaoEMEC")
    protected TInformacoesTramitacaoEMEC informacoesTramitacaoEMEC;

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link TTipoAtoComAtoProprio }
     *     
     */
    public TTipoAtoComAtoProprio getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTipoAtoComAtoProprio }
     *     
     */
    public void setTipo(TTipoAtoComAtoProprio value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumero(String value) {
        this.numero = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setData(XMLGregorianCalendar value) {
        this.data = value;
    }

    /**
     * Gets the value of the veiculoPublicacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVeiculoPublicacao() {
        return veiculoPublicacao;
    }

    /**
     * Sets the value of the veiculoPublicacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVeiculoPublicacao(String value) {
        this.veiculoPublicacao = value;
    }

    /**
     * Gets the value of the dataPublicacao property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataPublicacao() {
        return dataPublicacao;
    }

    /**
     * Sets the value of the dataPublicacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataPublicacao(XMLGregorianCalendar value) {
        this.dataPublicacao = value;
    }

    /**
     * Gets the value of the secaoPublicacao property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSecaoPublicacao() {
        return secaoPublicacao;
    }

    /**
     * Sets the value of the secaoPublicacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSecaoPublicacao(Long value) {
        this.secaoPublicacao = value;
    }

    /**
     * Gets the value of the paginaPublicacao property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPaginaPublicacao() {
        return paginaPublicacao;
    }

    /**
     * Sets the value of the paginaPublicacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPaginaPublicacao(Long value) {
        this.paginaPublicacao = value;
    }

    /**
     * Gets the value of the numeroDOU property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumeroDOU() {
        return numeroDOU;
    }

    /**
     * Sets the value of the numeroDOU property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumeroDOU(Long value) {
        this.numeroDOU = value;
    }

    /**
     * Gets the value of the informacoesTramitacaoEMEC property.
     * 
     * @return
     *     possible object is
     *     {@link TInformacoesTramitacaoEMEC }
     *     
     */
    public TInformacoesTramitacaoEMEC getInformacoesTramitacaoEMEC() {
        return informacoesTramitacaoEMEC;
    }

    /**
     * Sets the value of the informacoesTramitacaoEMEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInformacoesTramitacaoEMEC }
     *     
     */
    public void setInformacoesTramitacaoEMEC(TInformacoesTramitacaoEMEC value) {
        this.informacoesTramitacaoEMEC = value;
    }

}
