//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.fabricads.gov.handler.XMLGregorianCalendarAdapter;


/**
 * Dados do Diplomado
 * 
 * <p>Java class for TDadosDiplomado complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDadosDiplomado">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TId"/>
 *         &lt;group ref="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}GPessoa"/>
 *         &lt;element name="Nacionalidade" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNacionalidade"/>
 *         &lt;element name="Naturalidade" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNaturalidade"/>
 *         &lt;element name="CPF" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCpf"/>
 *         &lt;choice>
 *           &lt;element name="RG" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TRg"/>
 *           &lt;element name="OutroDocumentoIdentificacao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TOutroDocumentoIdentificacao"/>
 *         &lt;/choice>
 *         &lt;element name="DataNascimento" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDadosDiplomado", propOrder = {
    "id",
    "nome",
    "nomeSocial",
    "sexo",
    "nacionalidade",
    "naturalidade",
    "cpf",
    "rg",
    "outroDocumentoIdentificacao",
    "dataNascimento"
})
public class TDadosDiplomado {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Nome", required = true)
    protected String nome;
    @XmlElement(name = "NomeSocial")
    protected String nomeSocial;
    @XmlElement(name = "Sexo", required = true)
    @XmlSchemaType(name = "string")
    protected TSexo sexo;
    @XmlElement(name = "Nacionalidade", required = true)
    protected String nacionalidade;
    @XmlElement(name = "Naturalidade", required = true)
    protected TNaturalidade naturalidade;
    @XmlElement(name = "CPF", required = true)
    protected String cpf;
    @XmlElement(name = "RG")
    protected TRg rg;
    @XmlElement(name = "OutroDocumentoIdentificacao")
    protected TOutroDocumentoIdentificacao outroDocumentoIdentificacao;
    @XmlElement(name = "DataNascimento", required = true)
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(XMLGregorianCalendarAdapter.class)
    protected XMLGregorianCalendar dataNascimento;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the nomeSocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeSocial() {
        return nomeSocial;
    }

    /**
     * Sets the value of the nomeSocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeSocial(String value) {
        this.nomeSocial = value;
    }

    /**
     * Gets the value of the sexo property.
     * 
     * @return
     *     possible object is
     *     {@link TSexo }
     *     
     */
    public TSexo getSexo() {
        return sexo;
    }

    /**
     * Sets the value of the sexo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSexo }
     *     
     */
    public void setSexo(TSexo value) {
        this.sexo = value;
    }

    /**
     * Gets the value of the nacionalidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacionalidade() {
        return nacionalidade;
    }

    /**
     * Sets the value of the nacionalidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacionalidade(String value) {
        this.nacionalidade = value;
    }

    /**
     * Gets the value of the naturalidade property.
     * 
     * @return
     *     possible object is
     *     {@link TNaturalidade }
     *     
     */
    public TNaturalidade getNaturalidade() {
        return naturalidade;
    }

    /**
     * Sets the value of the naturalidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNaturalidade }
     *     
     */
    public void setNaturalidade(TNaturalidade value) {
        this.naturalidade = value;
    }

    /**
     * Gets the value of the cpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPF() {
        return cpf;
    }

    /**
     * Sets the value of the cpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPF(String value) {
        this.cpf = value;
    }

    /**
     * Gets the value of the rg property.
     * 
     * @return
     *     possible object is
     *     {@link TRg }
     *     
     */
    public TRg getRG() {
        return rg;
    }

    /**
     * Sets the value of the rg property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRg }
     *     
     */
    public void setRG(TRg value) {
        this.rg = value;
    }

    /**
     * Gets the value of the outroDocumentoIdentificacao property.
     * 
     * @return
     *     possible object is
     *     {@link TOutroDocumentoIdentificacao }
     *     
     */
    public TOutroDocumentoIdentificacao getOutroDocumentoIdentificacao() {
        return outroDocumentoIdentificacao;
    }

    /**
     * Sets the value of the outroDocumentoIdentificacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOutroDocumentoIdentificacao }
     *     
     */
    public void setOutroDocumentoIdentificacao(TOutroDocumentoIdentificacao value) {
        this.outroDocumentoIdentificacao = value;
    }

    /**
     * Gets the value of the dataNascimento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataNascimento() {
        return dataNascimento;
    }

    /**
     * Sets the value of the dataNascimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataNascimento(XMLGregorianCalendar value) {
        this.dataNascimento = value;
    }

}
