//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.10 at 04:01:49 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Dados da IES Emissora
 * 
 * <p>Java class for TDadosIesEmissora complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDadosIesEmissora">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Nome" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNomeIES"/>
 *         &lt;element name="CodigoMEC" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCodIESMEC"/>
 *         &lt;element name="CNPJ" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCnpj"/>
 *         &lt;element name="Endereco" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TEndereco"/>
 *         &lt;element name="Credenciamento" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TAtoRegulatorio"/>
 *         &lt;element name="Recredenciamento" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TAtoRegulatorio"/>
 *         &lt;element name="RenovacaoDeRecredenciamento" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TAtoRegulatorio" minOccurs="0"/>
 *         &lt;element name="Mantenedora" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RazaoSocial" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TRazaoSocial"/>
 *                   &lt;element name="CNPJ" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCnpj"/>
 *                   &lt;element name="Endereco" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TEndereco"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDadosIesEmissora", propOrder = {
    "nome",
    "codigoMEC",
    "cnpj",
    "endereco",
    "credenciamento",
    "recredenciamento",
    "renovacaoDeRecredenciamento",
    "mantenedora"
})
public class TDadosIesEmissora {

    @XmlElement(name = "Nome", required = true)
    protected String nome;
    @XmlElement(name = "CodigoMEC")
    @XmlSchemaType(name = "unsignedInt")
    protected long codigoMEC;
    @XmlElement(name = "CNPJ", required = true)
    protected String cnpj;
    @XmlElement(name = "Endereco", required = true)
    protected TEndereco endereco;
    @XmlElement(name = "Credenciamento", required = true)
    protected TAtoRegulatorio credenciamento;
    @XmlElement(name = "Recredenciamento", required = true)
    protected TAtoRegulatorio recredenciamento;
    @XmlElement(name = "RenovacaoDeRecredenciamento")
    protected TAtoRegulatorio renovacaoDeRecredenciamento;
    @XmlElement(name = "Mantenedora")
    protected TDadosIesEmissora.Mantenedora mantenedora;

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the codigoMEC property.
     * 
     */
    public long getCodigoMEC() {
        return codigoMEC;
    }

    /**
     * Sets the value of the codigoMEC property.
     * 
     */
    public void setCodigoMEC(long value) {
        this.codigoMEC = value;
    }

    /**
     * Gets the value of the cnpj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNPJ() {
        return cnpj;
    }

    /**
     * Sets the value of the cnpj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNPJ(String value) {
        this.cnpj = value;
    }

    /**
     * Gets the value of the endereco property.
     * 
     * @return
     *     possible object is
     *     {@link TEndereco }
     *     
     */
    public TEndereco getEndereco() {
        return endereco;
    }

    /**
     * Sets the value of the endereco property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEndereco }
     *     
     */
    public void setEndereco(TEndereco value) {
        this.endereco = value;
    }

    /**
     * Gets the value of the credenciamento property.
     * 
     * @return
     *     possible object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public TAtoRegulatorio getCredenciamento() {
        return credenciamento;
    }

    /**
     * Sets the value of the credenciamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public void setCredenciamento(TAtoRegulatorio value) {
        this.credenciamento = value;
    }

    /**
     * Gets the value of the recredenciamento property.
     * 
     * @return
     *     possible object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public TAtoRegulatorio getRecredenciamento() {
        return recredenciamento;
    }

    /**
     * Sets the value of the recredenciamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public void setRecredenciamento(TAtoRegulatorio value) {
        this.recredenciamento = value;
    }

    /**
     * Gets the value of the renovacaoDeRecredenciamento property.
     * 
     * @return
     *     possible object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public TAtoRegulatorio getRenovacaoDeRecredenciamento() {
        return renovacaoDeRecredenciamento;
    }

    /**
     * Sets the value of the renovacaoDeRecredenciamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public void setRenovacaoDeRecredenciamento(TAtoRegulatorio value) {
        this.renovacaoDeRecredenciamento = value;
    }

    /**
     * Gets the value of the mantenedora property.
     * 
     * @return
     *     possible object is
     *     {@link TDadosIesEmissora.Mantenedora }
     *     
     */
    public TDadosIesEmissora.Mantenedora getMantenedora() {
        return mantenedora;
    }

    /**
     * Sets the value of the mantenedora property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDadosIesEmissora.Mantenedora }
     *     
     */
    public void setMantenedora(TDadosIesEmissora.Mantenedora value) {
        this.mantenedora = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RazaoSocial" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TRazaoSocial"/>
     *         &lt;element name="CNPJ" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCnpj"/>
     *         &lt;element name="Endereco" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TEndereco"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "razaoSocial",
        "cnpj",
        "endereco"
    })
    public static class Mantenedora {

        @XmlElement(name = "RazaoSocial", required = true)
        protected String razaoSocial;
        @XmlElement(name = "CNPJ", required = true)
        protected String cnpj;
        @XmlElement(name = "Endereco", required = true)
        protected TEndereco endereco;

        /**
         * Gets the value of the razaoSocial property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRazaoSocial() {
            return razaoSocial;
        }

        /**
         * Sets the value of the razaoSocial property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRazaoSocial(String value) {
            this.razaoSocial = value;
        }

        /**
         * Gets the value of the cnpj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCNPJ() {
            return cnpj;
        }

        /**
         * Sets the value of the cnpj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCNPJ(String value) {
            this.cnpj = value;
        }

        /**
         * Gets the value of the endereco property.
         * 
         * @return
         *     possible object is
         *     {@link TEndereco }
         *     
         */
        public TEndereco getEndereco() {
            return endereco;
        }

        /**
         * Sets the value of the endereco property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEndereco }
         *     
         */
        public void setEndereco(TEndereco value) {
            this.endereco = value;
        }

    }

}
