//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.10 at 04:01:49 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.fabricads.gov.handler.XMLGregorianCalendarAdapter;


/**
 * Dados do Diplomado
 * 
 * <p>Java class for TDadosPrivadosDiplomado complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDadosPrivadosDiplomado">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Filiacao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TFiliacao"/>
 *         &lt;element name="HistoricoEscolar" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}THistoricoEscolar"/>
 *         &lt;element name="CargaHorariaCurso" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNumeroPositivo"/>
 *         &lt;element name="IngressoCurso">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Data" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *                   &lt;element name="FormaAcesso" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TFormaAcessoCurso"/>
 *                   &lt;element name="DataConclusao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDadosPrivadosDiplomado", propOrder = {
    "filiacao",
    "historicoEscolar",
    "cargaHorariaCurso",
    "ingressoCurso"
})
public class TDadosPrivadosDiplomado {

    @XmlElement(name = "Filiacao", required = true)
    protected TFiliacao filiacao;
    @XmlElement(name = "HistoricoEscolar", required = true)
    protected THistoricoEscolar historicoEscolar;
    @XmlElement(name = "CargaHorariaCurso")
    @XmlSchemaType(name = "unsignedInt")
    protected long cargaHorariaCurso;
    @XmlElement(name = "IngressoCurso", required = true)
    protected TDadosPrivadosDiplomado.IngressoCurso ingressoCurso;

    /**
     * Gets the value of the filiacao property.
     * 
     * @return
     *     possible object is
     *     {@link TFiliacao }
     *     
     */
    public TFiliacao getFiliacao() {
        return filiacao;
    }

    /**
     * Sets the value of the filiacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFiliacao }
     *     
     */
    public void setFiliacao(TFiliacao value) {
        this.filiacao = value;
    }

    /**
     * Gets the value of the historicoEscolar property.
     * 
     * @return
     *     possible object is
     *     {@link THistoricoEscolar }
     *     
     */
    public THistoricoEscolar getHistoricoEscolar() {
        return historicoEscolar;
    }

    /**
     * Sets the value of the historicoEscolar property.
     * 
     * @param value
     *     allowed object is
     *     {@link THistoricoEscolar }
     *     
     */
    public void setHistoricoEscolar(THistoricoEscolar value) {
        this.historicoEscolar = value;
    }

    /**
     * Gets the value of the cargaHorariaCurso property.
     * 
     */
    public long getCargaHorariaCurso() {
        return cargaHorariaCurso;
    }

    /**
     * Sets the value of the cargaHorariaCurso property.
     * 
     */
    public void setCargaHorariaCurso(long value) {
        this.cargaHorariaCurso = value;
    }

    /**
     * Gets the value of the ingressoCurso property.
     * 
     * @return
     *     possible object is
     *     {@link TDadosPrivadosDiplomado.IngressoCurso }
     *     
     */
    public TDadosPrivadosDiplomado.IngressoCurso getIngressoCurso() {
        return ingressoCurso;
    }

    /**
     * Sets the value of the ingressoCurso property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDadosPrivadosDiplomado.IngressoCurso }
     *     
     */
    public void setIngressoCurso(TDadosPrivadosDiplomado.IngressoCurso value) {
        this.ingressoCurso = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Data" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
     *         &lt;element name="FormaAcesso" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TFormaAcessoCurso"/>
     *         &lt;element name="DataConclusao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "data",
        "formaAcesso",
        "dataConclusao"
    })
    public static class IngressoCurso {

        @XmlElement(name = "Data", required = true)
        @XmlSchemaType(name = "date")
        @XmlJavaTypeAdapter(XMLGregorianCalendarAdapter.class)
        protected XMLGregorianCalendar data;
        @XmlElement(name = "FormaAcesso", required = true)
        @XmlSchemaType(name = "string")
        protected TFormaAcessoCurso formaAcesso;
        @XmlElement(name = "DataConclusao", required = true)
        @XmlSchemaType(name = "date")
        @XmlJavaTypeAdapter(XMLGregorianCalendarAdapter.class)
        protected XMLGregorianCalendar dataConclusao;

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setData(XMLGregorianCalendar value) {
            this.data = value;
        }

        /**
         * Gets the value of the formaAcesso property.
         * 
         * @return
         *     possible object is
         *     {@link TFormaAcessoCurso }
         *     
         */
        public TFormaAcessoCurso getFormaAcesso() {
            return formaAcesso;
        }

        /**
         * Sets the value of the formaAcesso property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFormaAcessoCurso }
         *     
         */
        public void setFormaAcesso(TFormaAcessoCurso value) {
            this.formaAcesso = value;
        }

        /**
         * Gets the value of the dataConclusao property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataConclusao() {
            return dataConclusao;
        }

        /**
         * Sets the value of the dataConclusao property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataConclusao(XMLGregorianCalendar value) {
            this.dataConclusao = value;
        }

    }

}
