//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.10 at 04:01:49 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Dados do curso
 * 
 * <p>Java class for TDadosCurso complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDadosCurso">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NomeCurso" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString"/>
 *         &lt;element name="CodigoCursoEMEC" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCodCursoMEC"/>
 *         &lt;element name="NomeHabilitacao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString"/>
 *         &lt;element name="Modalidade" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TModalidadeCurso"/>
 *         &lt;element name="TituloConferido" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TTituloConferido"/>
 *         &lt;element name="GrauConferido" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TGrauConferido"/>
 *         &lt;element name="EnderecoCurso" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TEndereco"/>
 *         &lt;element name="Polo" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TPolo" minOccurs="0"/>
 *         &lt;element name="Autorizacao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TAtoRegulatorio"/>
 *         &lt;element name="Reconhecimento" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TAtoRegulatorio"/>
 *         &lt;element name="RenovacaoReconhecimento" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TAtoRegulatorio" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDadosCurso", propOrder = {
    "nomeCurso",
    "codigoCursoEMEC",
    "nomeHabilitacao",
    "modalidade",
    "tituloConferido",
    "grauConferido",
    "enderecoCurso",
    "polo",
    "autorizacao",
    "reconhecimento",
    "renovacaoReconhecimento"
})
public class TDadosCurso {

    @XmlElement(name = "NomeCurso", required = true)
    protected String nomeCurso;
    @XmlElement(name = "CodigoCursoEMEC")
    @XmlSchemaType(name = "unsignedInt")
    protected long codigoCursoEMEC;
    @XmlElement(name = "NomeHabilitacao", required = true)
    protected String nomeHabilitacao;
    @XmlElement(name = "Modalidade", required = true)
    @XmlSchemaType(name = "string")
    protected TModalidadeCurso modalidade;
    @XmlElement(name = "TituloConferido", required = true)
    @XmlSchemaType(name = "string")
    protected TTituloConferido tituloConferido;
    @XmlElement(name = "GrauConferido", required = true)
    @XmlSchemaType(name = "string")
    protected TGrauConferido grauConferido;
    @XmlElement(name = "EnderecoCurso", required = true)
    protected TEndereco enderecoCurso;
    @XmlElement(name = "Polo")
    protected TPolo polo;
    @XmlElement(name = "Autorizacao", required = true)
    protected TAtoRegulatorio autorizacao;
    @XmlElement(name = "Reconhecimento", required = true)
    protected TAtoRegulatorio reconhecimento;
    @XmlElement(name = "RenovacaoReconhecimento")
    protected TAtoRegulatorio renovacaoReconhecimento;

    /**
     * Gets the value of the nomeCurso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeCurso() {
        return nomeCurso;
    }

    /**
     * Sets the value of the nomeCurso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeCurso(String value) {
        this.nomeCurso = value;
    }

    /**
     * Gets the value of the codigoCursoEMEC property.
     * 
     */
    public long getCodigoCursoEMEC() {
        return codigoCursoEMEC;
    }

    /**
     * Sets the value of the codigoCursoEMEC property.
     * 
     */
    public void setCodigoCursoEMEC(long value) {
        this.codigoCursoEMEC = value;
    }

    /**
     * Gets the value of the nomeHabilitacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeHabilitacao() {
        return nomeHabilitacao;
    }

    /**
     * Sets the value of the nomeHabilitacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeHabilitacao(String value) {
        this.nomeHabilitacao = value;
    }

    /**
     * Gets the value of the modalidade property.
     * 
     * @return
     *     possible object is
     *     {@link TModalidadeCurso }
     *     
     */
    public TModalidadeCurso getModalidade() {
        return modalidade;
    }

    /**
     * Sets the value of the modalidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link TModalidadeCurso }
     *     
     */
    public void setModalidade(TModalidadeCurso value) {
        this.modalidade = value;
    }

    /**
     * Gets the value of the tituloConferido property.
     * 
     * @return
     *     possible object is
     *     {@link TTituloConferido }
     *     
     */
    public TTituloConferido getTituloConferido() {
        return tituloConferido;
    }

    /**
     * Sets the value of the tituloConferido property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTituloConferido }
     *     
     */
    public void setTituloConferido(TTituloConferido value) {
        this.tituloConferido = value;
    }

    /**
     * Gets the value of the grauConferido property.
     * 
     * @return
     *     possible object is
     *     {@link TGrauConferido }
     *     
     */
    public TGrauConferido getGrauConferido() {
        return grauConferido;
    }

    /**
     * Sets the value of the grauConferido property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGrauConferido }
     *     
     */
    public void setGrauConferido(TGrauConferido value) {
        this.grauConferido = value;
    }

    /**
     * Gets the value of the enderecoCurso property.
     * 
     * @return
     *     possible object is
     *     {@link TEndereco }
     *     
     */
    public TEndereco getEnderecoCurso() {
        return enderecoCurso;
    }

    /**
     * Sets the value of the enderecoCurso property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEndereco }
     *     
     */
    public void setEnderecoCurso(TEndereco value) {
        this.enderecoCurso = value;
    }

    /**
     * Gets the value of the polo property.
     * 
     * @return
     *     possible object is
     *     {@link TPolo }
     *     
     */
    public TPolo getPolo() {
        return polo;
    }

    /**
     * Sets the value of the polo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPolo }
     *     
     */
    public void setPolo(TPolo value) {
        this.polo = value;
    }

    /**
     * Gets the value of the autorizacao property.
     * 
     * @return
     *     possible object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public TAtoRegulatorio getAutorizacao() {
        return autorizacao;
    }

    /**
     * Sets the value of the autorizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public void setAutorizacao(TAtoRegulatorio value) {
        this.autorizacao = value;
    }

    /**
     * Gets the value of the reconhecimento property.
     * 
     * @return
     *     possible object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public TAtoRegulatorio getReconhecimento() {
        return reconhecimento;
    }

    /**
     * Sets the value of the reconhecimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public void setReconhecimento(TAtoRegulatorio value) {
        this.reconhecimento = value;
    }

    /**
     * Gets the value of the renovacaoReconhecimento property.
     * 
     * @return
     *     possible object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public TAtoRegulatorio getRenovacaoReconhecimento() {
        return renovacaoReconhecimento;
    }

    /**
     * Sets the value of the renovacaoReconhecimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAtoRegulatorio }
     *     
     */
    public void setRenovacaoReconhecimento(TAtoRegulatorio value) {
        this.renovacaoReconhecimento = value;
    }

}
