//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2000._09.xmldsig_.SignatureType;


/**
 * Tipo de dados do registro do diploma digital flexibilizado para Universidades fora do sistema federal de ensino
 * 
 * <p>Java class for TDadosRegistroNSF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDadosRegistroNSF">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IesRegistradora" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TDadosIesRegistradora"/>
 *         &lt;element name="LivroRegistro" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TLivroRegistroNSF"/>
 *         &lt;element name="IdDocumentacaoAcademica">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}ID">
 *               &lt;pattern value="ReqDip[0-9]{44}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Seguranca" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TSeguranca"/>
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}ID">
 *             &lt;pattern value="RDip[0-9]{44}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDadosRegistroNSF", propOrder = {
    "iesRegistradora",
    "livroRegistro",
    "idDocumentacaoAcademica",
    "seguranca",
    "signature"
})
public class TDadosRegistroNSF {

    @XmlElement(name = "IesRegistradora", required = true)
    protected TDadosIesRegistradora iesRegistradora;
    @XmlElement(name = "LivroRegistro", required = true)
    protected TLivroRegistroNSF livroRegistro;
    @XmlElement(name = "IdDocumentacaoAcademica", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String idDocumentacaoAcademica;
    @XmlElement(name = "Seguranca", required = true)
    protected TSeguranca seguranca;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected List<SignatureType> signature;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the iesRegistradora property.
     * 
     * @return
     *     possible object is
     *     {@link TDadosIesRegistradora }
     *     
     */
    public TDadosIesRegistradora getIesRegistradora() {
        return iesRegistradora;
    }

    /**
     * Sets the value of the iesRegistradora property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDadosIesRegistradora }
     *     
     */
    public void setIesRegistradora(TDadosIesRegistradora value) {
        this.iesRegistradora = value;
    }

    /**
     * Gets the value of the livroRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link TLivroRegistroNSF }
     *     
     */
    public TLivroRegistroNSF getLivroRegistro() {
        return livroRegistro;
    }

    /**
     * Sets the value of the livroRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLivroRegistroNSF }
     *     
     */
    public void setLivroRegistro(TLivroRegistroNSF value) {
        this.livroRegistro = value;
    }

    /**
     * Gets the value of the idDocumentacaoAcademica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdDocumentacaoAcademica() {
        return idDocumentacaoAcademica;
    }

    /**
     * Sets the value of the idDocumentacaoAcademica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdDocumentacaoAcademica(String value) {
        this.idDocumentacaoAcademica = value;
    }

    /**
     * Gets the value of the seguranca property.
     * 
     * @return
     *     possible object is
     *     {@link TSeguranca }
     *     
     */
    public TSeguranca getSeguranca() {
        return seguranca;
    }

    /**
     * Sets the value of the seguranca property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSeguranca }
     *     
     */
    public void setSeguranca(TSeguranca value) {
        this.seguranca = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignatureType }
     * 
     * 
     */
    public List<SignatureType> getSignature() {
        if (signature == null) {
            signature = new ArrayList<SignatureType>();
        }
        return this.signature;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
