//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3._2000._09.xmldsig_.SignatureType;


/**
 * Tipo Documentação Acadêmica para Emissão e Registro
 * 
 * <p>Java class for TDocumentacaoAcademicaRegistro complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDocumentacaoAcademicaRegistro">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="RegistroReq" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TRegistroReq"/>
 *           &lt;element name="RegistroSegundaViaReq" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TRegistroSegundaViaReq"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDocumentacaoAcademicaRegistro", propOrder = {
    "registroReq",
    "registroSegundaViaReq",
    "signature"
})
public class TDocumentacaoAcademicaRegistro {

    @XmlElement(name = "RegistroReq")
    protected TRegistroReq registroReq;
    @XmlElement(name = "RegistroSegundaViaReq")
    protected TRegistroSegundaViaReq registroSegundaViaReq;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;

    /**
     * Gets the value of the registroReq property.
     * 
     * @return
     *     possible object is
     *     {@link TRegistroReq }
     *     
     */
    public TRegistroReq getRegistroReq() {
        return registroReq;
    }

    /**
     * Sets the value of the registroReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRegistroReq }
     *     
     */
    public void setRegistroReq(TRegistroReq value) {
        this.registroReq = value;
    }

    /**
     * Gets the value of the registroSegundaViaReq property.
     * 
     * @return
     *     possible object is
     *     {@link TRegistroSegundaViaReq }
     *     
     */
    public TRegistroSegundaViaReq getRegistroSegundaViaReq() {
        return registroSegundaViaReq;
    }

    /**
     * Sets the value of the registroSegundaViaReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRegistroSegundaViaReq }
     *     
     */
    public void setRegistroSegundaViaReq(TRegistroSegundaViaReq value) {
        this.registroSegundaViaReq = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

}
