//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Tipo Documentação Comprobatória
 * 
 * <p>Java class for TDocumentacaoComprobatoria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDocumentacaoComprobatoria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Documento" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd>TPdfA">
 *                 &lt;attribute name="tipo" use="required" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TTipoDocumentacao" />
 *                 &lt;attribute name="observacoes" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDocumentacaoComprobatoria", propOrder = {
    "documento"
})
public class TDocumentacaoComprobatoria {

    @XmlElement(name = "Documento", required = true)
    protected List<TDocumentacaoComprobatoria.Documento> documento;

    /**
     * Gets the value of the documento property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documento property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumento().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDocumentacaoComprobatoria.Documento }
     * 
     * 
     */
    public List<TDocumentacaoComprobatoria.Documento> getDocumento() {
        if (documento == null) {
            documento = new ArrayList<TDocumentacaoComprobatoria.Documento>();
        }
        return this.documento;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd>TPdfA">
     *       &lt;attribute name="tipo" use="required" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TTipoDocumentacao" />
     *       &lt;attribute name="observacoes" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Documento {

        @XmlValue
        protected byte[] value;
        @XmlAttribute(name = "tipo", required = true)
        protected TTipoDocumentacao tipo;
        @XmlAttribute(name = "observacoes")
        protected String observacoes;

        /**
         * Documento PDF/A segundo os padrões ISO 19005-1:2005 codificado em Base64
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setValue(byte[] value) {
            this.value = value;
        }

        /**
         * Gets the value of the tipo property.
         * 
         * @return
         *     possible object is
         *     {@link TTipoDocumentacao }
         *     
         */
        public TTipoDocumentacao getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TTipoDocumentacao }
         *     
         */
        public void setTipo(TTipoDocumentacao value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the observacoes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObservacoes() {
            return observacoes;
        }

        /**
         * Sets the value of the observacoes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObservacoes(String value) {
            this.observacoes = value;
        }

    }

}
