//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TGrauConferido.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TGrauConferido">
 *   &lt;restriction base="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString">
 *     &lt;enumeration value="Tecnólogo"/>
 *     &lt;enumeration value="Bacharelado"/>
 *     &lt;enumeration value="Licenciatura"/>
 *     &lt;enumeration value="Curso sequencial"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TGrauConferido")
@XmlEnum
public enum TGrauConferido {

    @XmlEnumValue("Tecn\u00f3logo")
    TECNÓLOGO("Tecn\u00f3logo"),
    @XmlEnumValue("Bacharelado")
    BACHARELADO("Bacharelado"),
    @XmlEnumValue("Licenciatura")
    LICENCIATURA("Licenciatura"),
    @XmlEnumValue("Curso sequencial")
    CURSO_SEQUENCIAL("Curso sequencial");
    private final String value;

    TGrauConferido(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TGrauConferido fromValue(String v) {
        for (TGrauConferido c: TGrauConferido.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
