//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.fabricads.gov.handler.XMLGregorianCalendarAdapter;


/**
 * Informações sobre tramitação de processos EMEC
 * 
 * <p>Java class for TInformacoesTramitacaoEMEC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TInformacoesTramitacaoEMEC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroProcesso" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNumeroPositivo"/>
 *         &lt;element name="TipoProcesso" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString"/>
 *         &lt;element name="DataCadastro" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *         &lt;element name="DataProtocolo" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TInformacoesTramitacaoEMEC", propOrder = {
    "numeroProcesso",
    "tipoProcesso",
    "dataCadastro",
    "dataProtocolo"
})
public class TInformacoesTramitacaoEMEC {

    @XmlElement(name = "NumeroProcesso")
    @XmlSchemaType(name = "unsignedInt")
    protected long numeroProcesso;
    @XmlElement(name = "TipoProcesso", required = true)
    protected String tipoProcesso;
    @XmlElement(name = "DataCadastro", required = true)
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(XMLGregorianCalendarAdapter.class)
    protected XMLGregorianCalendar dataCadastro;
    @XmlElement(name = "DataProtocolo", required = true)
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(XMLGregorianCalendarAdapter.class)
    protected XMLGregorianCalendar dataProtocolo;

    /**
     * Gets the value of the numeroProcesso property.
     * 
     */
    public long getNumeroProcesso() {
        return numeroProcesso;
    }

    /**
     * Sets the value of the numeroProcesso property.
     * 
     */
    public void setNumeroProcesso(long value) {
        this.numeroProcesso = value;
    }

    /**
     * Gets the value of the tipoProcesso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoProcesso() {
        return tipoProcesso;
    }

    /**
     * Sets the value of the tipoProcesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoProcesso(String value) {
        this.tipoProcesso = value;
    }

    /**
     * Gets the value of the dataCadastro property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataCadastro() {
        return dataCadastro;
    }

    /**
     * Sets the value of the dataCadastro property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataCadastro(XMLGregorianCalendar value) {
        this.dataCadastro = value;
    }

    /**
     * Gets the value of the dataProtocolo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataProtocolo() {
        return dataProtocolo;
    }

    /**
     * Sets the value of the dataProtocolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataProtocolo(XMLGregorianCalendar value) {
        this.dataProtocolo = value;
    }

}
