//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.10 at 04:01:49 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Dados do livro
 * 
 * <p>Java class for TLivroRegistro complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TLivroRegistro">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LivroRegistro" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCodLivroRegistro"/>
 *         &lt;element name="NumeroFolhaDoDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNumFolhaDoDiploma"/>
 *         &lt;element name="NumeroSequenciaDoDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNumSequenciaDiploma"/>
 *         &lt;element name="ProcessoDoDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCodProcessoDoDiploma"/>
 *         &lt;element name="DataColacaoGrau" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *         &lt;element name="DataExpedicaoDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *         &lt;element name="DataRegistroDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *         &lt;element name="ResponsavelRegistro">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Nome" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNome"/>
 *                   &lt;element name="CPF" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCpf"/>
 *                   &lt;element name="IDouNumeroMatricula" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TId"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TLivroRegistro", propOrder = {
    "livroRegistro",
    "numeroFolhaDoDiploma",
    "numeroSequenciaDoDiploma",
    "processoDoDiploma",
    "dataColacaoGrau",
    "dataExpedicaoDiploma",
    "dataRegistroDiploma",
    "responsavelRegistro"
})
public class TLivroRegistro {

    @XmlElement(name = "LivroRegistro", required = true)
    protected String livroRegistro;
    @XmlElement(name = "NumeroFolhaDoDiploma", required = true)
    protected String numeroFolhaDoDiploma;
    @XmlElement(name = "NumeroSequenciaDoDiploma", required = true)
    protected String numeroSequenciaDoDiploma;
    @XmlElement(name = "ProcessoDoDiploma", required = true)
    protected String processoDoDiploma;
    @XmlElement(name = "DataColacaoGrau", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataColacaoGrau;
    @XmlElement(name = "DataExpedicaoDiploma", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataExpedicaoDiploma;
    @XmlElement(name = "DataRegistroDiploma", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataRegistroDiploma;
    @XmlElement(name = "ResponsavelRegistro", required = true)
    protected TLivroRegistro.ResponsavelRegistro responsavelRegistro;

    /**
     * Gets the value of the livroRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLivroRegistro() {
        return livroRegistro;
    }

    /**
     * Sets the value of the livroRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLivroRegistro(String value) {
        this.livroRegistro = value;
    }

    /**
     * Gets the value of the numeroFolhaDoDiploma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroFolhaDoDiploma() {
        return numeroFolhaDoDiploma;
    }

    /**
     * Sets the value of the numeroFolhaDoDiploma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroFolhaDoDiploma(String value) {
        this.numeroFolhaDoDiploma = value;
    }

    /**
     * Gets the value of the numeroSequenciaDoDiploma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroSequenciaDoDiploma() {
        return numeroSequenciaDoDiploma;
    }

    /**
     * Sets the value of the numeroSequenciaDoDiploma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroSequenciaDoDiploma(String value) {
        this.numeroSequenciaDoDiploma = value;
    }

    /**
     * Gets the value of the processoDoDiploma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessoDoDiploma() {
        return processoDoDiploma;
    }

    /**
     * Sets the value of the processoDoDiploma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessoDoDiploma(String value) {
        this.processoDoDiploma = value;
    }

    /**
     * Gets the value of the dataColacaoGrau property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataColacaoGrau() {
        return dataColacaoGrau;
    }

    /**
     * Sets the value of the dataColacaoGrau property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataColacaoGrau(XMLGregorianCalendar value) {
        this.dataColacaoGrau = value;
    }

    /**
     * Gets the value of the dataExpedicaoDiploma property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataExpedicaoDiploma() {
        return dataExpedicaoDiploma;
    }

    /**
     * Sets the value of the dataExpedicaoDiploma property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataExpedicaoDiploma(XMLGregorianCalendar value) {
        this.dataExpedicaoDiploma = value;
    }

    /**
     * Gets the value of the dataRegistroDiploma property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataRegistroDiploma() {
        return dataRegistroDiploma;
    }

    /**
     * Sets the value of the dataRegistroDiploma property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataRegistroDiploma(XMLGregorianCalendar value) {
        this.dataRegistroDiploma = value;
    }

    /**
     * Gets the value of the responsavelRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link TLivroRegistro.ResponsavelRegistro }
     *     
     */
    public TLivroRegistro.ResponsavelRegistro getResponsavelRegistro() {
        return responsavelRegistro;
    }

    /**
     * Sets the value of the responsavelRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLivroRegistro.ResponsavelRegistro }
     *     
     */
    public void setResponsavelRegistro(TLivroRegistro.ResponsavelRegistro value) {
        this.responsavelRegistro = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Nome" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNome"/>
     *         &lt;element name="CPF" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCpf"/>
     *         &lt;element name="IDouNumeroMatricula" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TId"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nome",
        "cpf",
        "iDouNumeroMatricula"
    })
    public static class ResponsavelRegistro {

        @XmlElement(name = "Nome", required = true)
        protected String nome;
        @XmlElement(name = "CPF", required = true)
        protected String cpf;
        @XmlElement(name = "IDouNumeroMatricula", required = true)
        protected String iDouNumeroMatricula;

        /**
         * Gets the value of the nome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNome() {
            return nome;
        }

        /**
         * Sets the value of the nome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNome(String value) {
            this.nome = value;
        }

        /**
         * Gets the value of the cpf property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCPF() {
            return cpf;
        }

        /**
         * Sets the value of the cpf property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCPF(String value) {
            this.cpf = value;
        }

        /**
         * Gets the value of the iDouNumeroMatricula property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIDouNumeroMatricula() {
            return iDouNumeroMatricula;
        }

        /**
         * Sets the value of the iDouNumeroMatricula property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIDouNumeroMatricula(String value) {
            this.iDouNumeroMatricula = value;
        }

    }

}
