//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Dados do livro
 * 
 * <p>Java class for TLivroRegistroNSF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TLivroRegistroNSF">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LivroRegistro" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCodLivroRegistro" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="NumeroRegistro" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TId"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="NumeroFolhaDoDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNumFolhaDoDiploma"/>
 *             &lt;element name="NumeroSequenciaDoDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNumSequenciaDiploma"/>
 *             &lt;element name="NumeroRegistro" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TId" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="ProcessoDoDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCodProcessoDoDiploma" minOccurs="0"/>
 *         &lt;element name="DataColacaoGrau" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *         &lt;element name="DataExpedicaoDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *         &lt;element name="DataRegistroDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TData"/>
 *         &lt;element name="ResponsavelRegistro">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Nome" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNome"/>
 *                   &lt;element name="CPF" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCpf"/>
 *                   &lt;element name="IDouNumeroMatricula" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TId" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TLivroRegistroNSF", propOrder = {
    "content"
})
public class TLivroRegistroNSF {

    @XmlElementRefs({
        @XmlElementRef(name = "NumeroRegistro", namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DataColacaoGrau", namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DataExpedicaoDiploma", namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LivroRegistro", namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NumeroFolhaDoDiploma", namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NumeroSequenciaDoDiploma", namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DataRegistroDiploma", namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ProcessoDoDiploma", namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ResponsavelRegistro", namespace = "http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "NumeroRegistro" is used by two different parts of a schema. See: 
     * line 331 of file:/mnt/c/git/DiplomaDigitalModel/schema/leiauteDiplomaDigital_v1.02.xsd
     * line 326 of file:/mnt/c/git/DiplomaDigitalModel/schema/leiauteDiplomaDigital_v1.02.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TLivroRegistroNSF.ResponsavelRegistro }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Nome" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TNome"/>
     *         &lt;element name="CPF" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCpf"/>
     *         &lt;element name="IDouNumeroMatricula" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TId" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nome",
        "cpf",
        "iDouNumeroMatricula"
    })
    public static class ResponsavelRegistro {

        @XmlElement(name = "Nome", required = true)
        protected String nome;
        @XmlElement(name = "CPF", required = true)
        protected String cpf;
        @XmlElement(name = "IDouNumeroMatricula")
        protected String iDouNumeroMatricula;

        /**
         * Gets the value of the nome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNome() {
            return nome;
        }

        /**
         * Sets the value of the nome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNome(String value) {
            this.nome = value;
        }

        /**
         * Gets the value of the cpf property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCPF() {
            return cpf;
        }

        /**
         * Sets the value of the cpf property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCPF(String value) {
            this.cpf = value;
        }

        /**
         * Gets the value of the iDouNumeroMatricula property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIDouNumeroMatricula() {
            return iDouNumeroMatricula;
        }

        /**
         * Sets the value of the iDouNumeroMatricula property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIDouNumeroMatricula(String value) {
            this.iDouNumeroMatricula = value;
        }

    }

}
