//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Dados do polo
 * 
 * <p>Java class for TPolo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPolo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Nome" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString"/>
 *         &lt;element name="Endereco" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TEndereco"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="CodigoEMEC" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TCodPoloMEC"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="SemCodigoEMEC" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TInformacoesTramitacaoEMEC"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPolo", propOrder = {
    "nome",
    "endereco",
    "codigoEMEC",
    "semCodigoEMEC"
})
public class TPolo {

    @XmlElement(name = "Nome", required = true)
    protected String nome;
    @XmlElement(name = "Endereco", required = true)
    protected TEndereco endereco;
    @XmlElement(name = "CodigoEMEC")
    @XmlSchemaType(name = "unsignedInt")
    protected Long codigoEMEC;
    @XmlElement(name = "SemCodigoEMEC")
    protected TInformacoesTramitacaoEMEC semCodigoEMEC;

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the endereco property.
     * 
     * @return
     *     possible object is
     *     {@link TEndereco }
     *     
     */
    public TEndereco getEndereco() {
        return endereco;
    }

    /**
     * Sets the value of the endereco property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEndereco }
     *     
     */
    public void setEndereco(TEndereco value) {
        this.endereco = value;
    }

    /**
     * Gets the value of the codigoEMEC property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCodigoEMEC() {
        return codigoEMEC;
    }

    /**
     * Sets the value of the codigoEMEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCodigoEMEC(Long value) {
        this.codigoEMEC = value;
    }

    /**
     * Gets the value of the semCodigoEMEC property.
     * 
     * @return
     *     possible object is
     *     {@link TInformacoesTramitacaoEMEC }
     *     
     */
    public TInformacoesTramitacaoEMEC getSemCodigoEMEC() {
        return semCodigoEMEC;
    }

    /**
     * Sets the value of the semCodigoEMEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInformacoesTramitacaoEMEC }
     *     
     */
    public void setSemCodigoEMEC(TInformacoesTramitacaoEMEC value) {
        this.semCodigoEMEC = value;
    }

}
