//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Tipo Requisição de Registro de Diploma Digital como segunda via de um diploma físico
 * 
 * <p>Java class for TRegistroSegundaViaReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TRegistroSegundaViaReq">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="DadosDiploma" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TDadosDiploma"/>
 *           &lt;element name="DadosDiplomaNSF" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TDadosDiplomaNSF"/>
 *         &lt;/choice>
 *         &lt;element name="DadosPrivadosDiplomado" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TDadosPrivadosDiplomadoSegundaVia"/>
 *         &lt;element name="TermoResponsabilidade" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TTermoResponsabilidade" minOccurs="0"/>
 *         &lt;element name="DocumentacaoComprobatoria" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TDocumentacaoComprobatoria" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="versao" use="required" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TVersao" />
 *       &lt;attribute name="id" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}ID">
 *             &lt;pattern value="ReqDip[0-9]{44}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRegistroSegundaViaReq", propOrder = {
    "dadosDiploma",
    "dadosDiplomaNSF",
    "dadosPrivadosDiplomado",
    "termoResponsabilidade",
    "documentacaoComprobatoria"
})
public class TRegistroSegundaViaReq {

    @XmlElement(name = "DadosDiploma")
    protected TDadosDiploma dadosDiploma;
    @XmlElement(name = "DadosDiplomaNSF")
    protected TDadosDiplomaNSF dadosDiplomaNSF;
    @XmlElement(name = "DadosPrivadosDiplomado", required = true)
    protected TDadosPrivadosDiplomadoSegundaVia dadosPrivadosDiplomado;
    @XmlElement(name = "TermoResponsabilidade")
    protected TTermoResponsabilidade termoResponsabilidade;
    @XmlElement(name = "DocumentacaoComprobatoria")
    protected TDocumentacaoComprobatoria documentacaoComprobatoria;
    @XmlAttribute(name = "versao", required = true)
    protected String versao;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the dadosDiploma property.
     * 
     * @return
     *     possible object is
     *     {@link TDadosDiploma }
     *     
     */
    public TDadosDiploma getDadosDiploma() {
        return dadosDiploma;
    }

    /**
     * Sets the value of the dadosDiploma property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDadosDiploma }
     *     
     */
    public void setDadosDiploma(TDadosDiploma value) {
        this.dadosDiploma = value;
    }

    /**
     * Gets the value of the dadosDiplomaNSF property.
     * 
     * @return
     *     possible object is
     *     {@link TDadosDiplomaNSF }
     *     
     */
    public TDadosDiplomaNSF getDadosDiplomaNSF() {
        return dadosDiplomaNSF;
    }

    /**
     * Sets the value of the dadosDiplomaNSF property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDadosDiplomaNSF }
     *     
     */
    public void setDadosDiplomaNSF(TDadosDiplomaNSF value) {
        this.dadosDiplomaNSF = value;
    }

    /**
     * Gets the value of the dadosPrivadosDiplomado property.
     * 
     * @return
     *     possible object is
     *     {@link TDadosPrivadosDiplomadoSegundaVia }
     *     
     */
    public TDadosPrivadosDiplomadoSegundaVia getDadosPrivadosDiplomado() {
        return dadosPrivadosDiplomado;
    }

    /**
     * Sets the value of the dadosPrivadosDiplomado property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDadosPrivadosDiplomadoSegundaVia }
     *     
     */
    public void setDadosPrivadosDiplomado(TDadosPrivadosDiplomadoSegundaVia value) {
        this.dadosPrivadosDiplomado = value;
    }

    /**
     * Gets the value of the termoResponsabilidade property.
     * 
     * @return
     *     possible object is
     *     {@link TTermoResponsabilidade }
     *     
     */
    public TTermoResponsabilidade getTermoResponsabilidade() {
        return termoResponsabilidade;
    }

    /**
     * Sets the value of the termoResponsabilidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTermoResponsabilidade }
     *     
     */
    public void setTermoResponsabilidade(TTermoResponsabilidade value) {
        this.termoResponsabilidade = value;
    }

    /**
     * Gets the value of the documentacaoComprobatoria property.
     * 
     * @return
     *     possible object is
     *     {@link TDocumentacaoComprobatoria }
     *     
     */
    public TDocumentacaoComprobatoria getDocumentacaoComprobatoria() {
        return documentacaoComprobatoria;
    }

    /**
     * Sets the value of the documentacaoComprobatoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDocumentacaoComprobatoria }
     *     
     */
    public void setDocumentacaoComprobatoria(TDocumentacaoComprobatoria value) {
        this.documentacaoComprobatoria = value;
    }

    /**
     * Gets the value of the versao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersao() {
        return versao;
    }

    /**
     * Sets the value of the versao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersao(String value) {
        this.versao = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
