//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo situação do aluno no ENADE. Deve-se utilizar a Situação excplicitada na enumeração a menos que não esteja disposível. Neste caso deve-se usar a opção "Outros
 * 
 * <p>Java class for TSituacaoAlunoEnadeHistorico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSituacaoAlunoEnadeHistorico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Situacao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TEnumSituacaoAlunoEnadeHistorico"/>
 *         &lt;element name="OutraSituacao" type="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSituacaoAlunoEnadeHistorico", propOrder = {
    "situacao",
    "outraSituacao"
})
public class TSituacaoAlunoEnadeHistorico {

    @XmlElement(name = "Situacao")
    @XmlSchemaType(name = "string")
    protected TEnumSituacaoAlunoEnadeHistorico situacao;
    @XmlElement(name = "OutraSituacao")
    protected String outraSituacao;

    /**
     * Gets the value of the situacao property.
     * 
     * @return
     *     possible object is
     *     {@link TEnumSituacaoAlunoEnadeHistorico }
     *     
     */
    public TEnumSituacaoAlunoEnadeHistorico getSituacao() {
        return situacao;
    }

    /**
     * Sets the value of the situacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEnumSituacaoAlunoEnadeHistorico }
     *     
     */
    public void setSituacao(TEnumSituacaoAlunoEnadeHistorico value) {
        this.situacao = value;
    }

    /**
     * Gets the value of the outraSituacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutraSituacao() {
        return outraSituacao;
    }

    /**
     * Sets the value of the outraSituacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutraSituacao(String value) {
        this.outraSituacao = value;
    }

}
