//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.10 at 04:01:49 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TSituacaoAlunoEnadeHistorico.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TSituacaoAlunoEnadeHistorico">
 *   &lt;restriction base="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString">
 *     &lt;enumeration value="IRREGULAR"/>
 *     &lt;enumeration value="Ingressante / Participante"/>
 *     &lt;enumeration value="Dispensado, em razão do calendário trienal"/>
 *     &lt;enumeration value="Concluinte / Participante"/>
 *     &lt;enumeration value="Dispensado pelo MEC"/>
 *     &lt;enumeration value="Dispensado, em razão da natureza do curso"/>
 *     &lt;enumeration value="Dispensado, por razão de ordem pessoal"/>
 *     &lt;enumeration value="Dispensado, por ato da instituição de ensino"/>
 *     &lt;enumeration value="Dispensado, em razão de mobilidade acadêmica no exterior"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TSituacaoAlunoEnadeHistorico")
@XmlEnum
public enum TSituacaoAlunoEnadeHistorico {

    IRREGULAR("IRREGULAR"),
    @XmlEnumValue("Ingressante / Participante")
    INGRESSANTE_PARTICIPANTE("Ingressante / Participante"),
    @XmlEnumValue("Dispensado, em raz\u00e3o do calend\u00e1rio trienal")
    DISPENSADO_EM_RAZÃO_DO_CALENDÁRIO_TRIENAL("Dispensado, em raz\u00e3o do calend\u00e1rio trienal"),
    @XmlEnumValue("Concluinte / Participante")
    CONCLUINTE_PARTICIPANTE("Concluinte / Participante"),
    @XmlEnumValue("Dispensado pelo MEC")
    DISPENSADO_PELO_MEC("Dispensado pelo MEC"),
    @XmlEnumValue("Dispensado, em raz\u00e3o da natureza do curso")
    DISPENSADO_EM_RAZÃO_DA_NATUREZA_DO_CURSO("Dispensado, em raz\u00e3o da natureza do curso"),
    @XmlEnumValue("Dispensado, por raz\u00e3o de ordem pessoal")
    DISPENSADO_POR_RAZÃO_DE_ORDEM_PESSOAL("Dispensado, por raz\u00e3o de ordem pessoal"),
    @XmlEnumValue("Dispensado, por ato da institui\u00e7\u00e3o de ensino")
    DISPENSADO_POR_ATO_DA_INSTITUIÇÃO_DE_ENSINO("Dispensado, por ato da institui\u00e7\u00e3o de ensino"),
    @XmlEnumValue("Dispensado, em raz\u00e3o de mobilidade acad\u00eamica no exterior")
    DISPENSADO_EM_RAZÃO_DE_MOBILIDADE_ACADÊMICA_NO_EXTERIOR("Dispensado, em raz\u00e3o de mobilidade acad\u00eamica no exterior");
    private final String value;

    TSituacaoAlunoEnadeHistorico(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TSituacaoAlunoEnadeHistorico fromValue(String v) {
        for (TSituacaoAlunoEnadeHistorico c: TSituacaoAlunoEnadeHistorico.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
