//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.10 at 04:01:49 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTipoDocumentacao.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TTipoDocumentacao">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="TermoResponsabilidade"/>
 *     &lt;enumeration value="DocumentoIdentidadeDoAluno"/>
 *     &lt;enumeration value="ProvaConclusaoEnsinoMedio"/>
 *     &lt;enumeration value="HistoricoEscolar"/>
 *     &lt;enumeration value="ProvaColacao"/>
 *     &lt;enumeration value="ComprovacaoEstagioCurricular"/>
 *     &lt;enumeration value="CertidaoNascimento"/>
 *     &lt;enumeration value="CertidaoCasamento"/>
 *     &lt;enumeration value="TituloEleitor"/>
 *     &lt;enumeration value="AtoNaturalizacao"/>
 *     &lt;enumeration value="Outros"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TTipoDocumentacao")
@XmlEnum
public enum TTipoDocumentacao {

    @XmlEnumValue("TermoResponsabilidade")
    TERMO_RESPONSABILIDADE("TermoResponsabilidade"),
    @XmlEnumValue("DocumentoIdentidadeDoAluno")
    DOCUMENTO_IDENTIDADE_DO_ALUNO("DocumentoIdentidadeDoAluno"),
    @XmlEnumValue("ProvaConclusaoEnsinoMedio")
    PROVA_CONCLUSAO_ENSINO_MEDIO("ProvaConclusaoEnsinoMedio"),
    @XmlEnumValue("HistoricoEscolar")
    HISTORICO_ESCOLAR("HistoricoEscolar"),
    @XmlEnumValue("ProvaColacao")
    PROVA_COLACAO("ProvaColacao"),
    @XmlEnumValue("ComprovacaoEstagioCurricular")
    COMPROVACAO_ESTAGIO_CURRICULAR("ComprovacaoEstagioCurricular"),
    @XmlEnumValue("CertidaoNascimento")
    CERTIDAO_NASCIMENTO("CertidaoNascimento"),
    @XmlEnumValue("CertidaoCasamento")
    CERTIDAO_CASAMENTO("CertidaoCasamento"),
    @XmlEnumValue("TituloEleitor")
    TITULO_ELEITOR("TituloEleitor"),
    @XmlEnumValue("AtoNaturalizacao")
    ATO_NATURALIZACAO("AtoNaturalizacao"),
    @XmlEnumValue("Outros")
    OUTROS("Outros");
    private final String value;

    TTipoDocumentacao(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTipoDocumentacao fromValue(String v) {
        for (TTipoDocumentacao c: TTipoDocumentacao.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
