//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTipoAtoComAtoProprio.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TTipoAtoComAtoProprio">
 *   &lt;restriction base="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString">
 *     &lt;enumeration value="Parecer"/>
 *     &lt;enumeration value="Resolução"/>
 *     &lt;enumeration value="Decreto"/>
 *     &lt;enumeration value="Portaria"/>
 *     &lt;enumeration value="Lei Federal"/>
 *     &lt;enumeration value="Lei Estadual"/>
 *     &lt;enumeration value="Lei Municipal"/>
 *     &lt;enumeration value="Ato Próprio"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TTipoAtoComAtoProprio")
@XmlEnum
public enum TTipoAtoComAtoProprio {

    @XmlEnumValue("Parecer")
    PARECER("Parecer"),
    @XmlEnumValue("Resolu\u00e7\u00e3o")
    RESOLUÇÃO("Resolu\u00e7\u00e3o"),
    @XmlEnumValue("Decreto")
    DECRETO("Decreto"),
    @XmlEnumValue("Portaria")
    PORTARIA("Portaria"),
    @XmlEnumValue("Lei Federal")
    LEI_FEDERAL("Lei Federal"),
    @XmlEnumValue("Lei Estadual")
    LEI_ESTADUAL("Lei Estadual"),
    @XmlEnumValue("Lei Municipal")
    LEI_MUNICIPAL("Lei Municipal"),
    @XmlEnumValue("Ato Pr\u00f3prio")
    ATO_PRÓPRIO("Ato Pr\u00f3prio");
    private final String value;

    TTipoAtoComAtoProprio(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTipoAtoComAtoProprio fromValue(String v) {
        for (TTipoAtoComAtoProprio c: TTipoAtoComAtoProprio.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
