//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.20 at 12:04:39 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTitulo.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TTitulo">
 *   &lt;restriction base="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString">
 *     &lt;enumeration value="Licenciado"/>
 *     &lt;enumeration value="Técnico"/>
 *     &lt;enumeration value="Bacharel"/>
 *     &lt;enumeration value="Médico"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TTitulo")
@XmlEnum
public enum TTitulo {

    @XmlEnumValue("Licenciado")
    LICENCIADO("Licenciado"),
    @XmlEnumValue("T\u00e9cnico")
    TÉCNICO("T\u00e9cnico"),
    @XmlEnumValue("Bacharel")
    BACHAREL("Bacharel"),
    @XmlEnumValue("M\u00e9dico")
    MÉDICO("M\u00e9dico");
    private final String value;

    TTitulo(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTitulo fromValue(String v) {
        for (TTitulo c: TTitulo.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
