//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.10 at 04:01:49 AM BRT 
//


package br.gov.mec.portal.diplomadigital.arquivos_em_xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTitulacao.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TTitulacao">
 *   &lt;restriction base="{http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd}TString">
 *     &lt;whiteSpace value="preserve"/>
 *     &lt;enumeration value="Graduação"/>
 *     &lt;enumeration value="Especialização"/>
 *     &lt;enumeration value="Mestrado"/>
 *     &lt;enumeration value="Doutorado"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TTitulacao")
@XmlEnum
public enum TTitulacao {

    @XmlEnumValue("Gradua\u00e7\u00e3o")
    GRADUAÇÃO("Gradua\u00e7\u00e3o"),
    @XmlEnumValue("Especializa\u00e7\u00e3o")
    ESPECIALIZAÇÃO("Especializa\u00e7\u00e3o"),
    @XmlEnumValue("Mestrado")
    MESTRADO("Mestrado"),
    @XmlEnumValue("Doutorado")
    DOUTORADO("Doutorado");
    private final String value;

    TTitulacao(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTitulacao fromValue(String v) {
        for (TTitulacao c: TTitulacao.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
